# Home Work One - ML Zoomcamp 2026

Hi, I'm Norman! This is my submission for Home Work 1 for ML ZoomCamp 2026.

Let’s connect on [LinkedIn](https://www.linkedin.com/in/anormanangel/) and [Twitter](https://x.com/anormanangel) to keep learning together.

In [1]:
import pandas as pd
import numpy as np

In [3]:


df = pd.read_csv('https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv')

df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

### Q1. Pandas version: What version of Pandas did you install?

In [4]:
pd.__version__

'3.0.1'

### Q2. Records count: How many records are in the dataset?

In [5]:
df.shape

(10000, 11)

### Q3. Fuel types: How many fuel types are presented in the dataset?

In [6]:
df['fuel_type'].nunique()

3

### Q4. Missing values: How many columns in the dataset have missing values?

In [9]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [10]:
(df.isnull().sum() > 0).sum()

2

Q5. Max fuel efficiency: What's the maximum fuel efficiency of cars from Asia?

In [12]:
df[df['origin'] == 'Asia']['fuel_efficiency_mpg'].max()

41.2

### Q6. Median value of horsepower
- Find the median value of the horsepower column in the dataset.
- Next, calculate the most frequent value of the same horsepower column.
- Use the fillna method to fill the missing values in the horsepower column with the most frequent value from the previous step.
#### Now, calculate the median value of horsepower once again.
- Has it changed?

-Yes, it increased
- Yes, it decreased
- No

In [21]:
# Median horse power: Most Frequent

df['horsepower'].median()

254.0

In [22]:
# Most Frequent horse power: Mode

df['horsepower'].mode()

0    252.0
Name: horsepower, dtype: float64

In [24]:
# Filling missin values in horsepower column with mode

df['horsepower'] = df['horsepower'].fillna(df['horsepower'].mode()[0])

In [26]:
# Calculate the median again

df['horsepower'].median()

252.0

### 07. Sum of Weights

In [29]:
# Select all cars from Asia

df_asia = df[df['origin'] == 'Asia']

In [30]:
# Select vehicle_weight and model_year

X = df_asia[['vehicle_weight', 'model_year']]

In [ ]:
# Sellect the first 7 rows

X = X.head(7)

In [32]:
# Get the underlying NumPy array. Let's call it X

X

      vehicle_weight  model_year
2               4240        1996
6               4310        1992
8               4230        1997
10              4420        1978
15              3950        2007
...              ...         ...
9984            4610        2011
9987            4530        2004
9990            3630        1975
9994            4610        1993
9996            4370        1993

[2994 rows x 2 columns]

In [33]:
# Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.

X = df[df['origin'] == 'Asia'][['vehicle_weight', 'model_year']].head(7).values

In [37]:
XTX = X.T @ X

XTX

array([[131950500,  60750580],
       [ 60750580,  28041424]])

In [40]:
# Invert XTX

XTX_inv = np.linalg.inv(XTX)

In [42]:
# Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200]

y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [43]:
# Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.

w = XTX_inv @ X.T @ y

In [44]:
# Sum of elements w

w.sum()

0.3691969690492758